# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_name',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
