# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-26 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_auto_20190326_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=1000),
        ),
    ]
